In [2]:

%matplotlib inline
from __future__ import print_function
from __future__ import division

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Load dataset

In [12]:
# load the provided data
X = pd.read_csv('../data/01_raw/dengue_features_train.csv',
                             index_col=[0,1,2])

y = pd.read_csv('../data/01_raw/dengue_labels_train.csv',
                           index_col=[0,1,2])

In [13]:
print('features: ', X.shape)
print('labels  : ', y.shape)

features:  (1456, 21)
labels  :  (1456, 1)

In [15]:
X

                     week_start_date   ndvi_ne   ndvi_nw   ndvi_se   ndvi_sw  \
city year weekofyear
sj   1990 18              1990-04-30  0.122600  0.103725  0.198483  0.177617
          19              1990-05-07  0.169900  0.142175  0.162357  0.155486
          20              1990-05-14  0.032250  0.172967  0.157200  0.170843
          21              1990-05-21  0.128633  0.245067  0.227557  0.235886
          22              1990-05-28  0.196200  0.262200  0.251200  0.247340
...                              ...       ...       ...       ...       ...
iq   2010 21              2010-05-28  0.342750  0.318900  0.256343  0.292514
          22              2010-06-04  0.160157  0.160371  0.136043  0.225657
          23              2010-06-11  0.247057  0.146057  0.250357  0.233714
          24              2010-06-18  0.333914  0.245771  0.278886  0.325486
          25              2010-06-25  0.298186  0.232971  0.274214  0.315757

                      precipitation_amt_mm  reanalysis_air_temp_k  \
city year weekofyear
sj   1990 18                         12.42             297.572857
          19                         22.82             298.211429
          20                         34.54             298.781429
          21                         15.36             298.987143
          22                          7.52             299.518571
...                                    ...                    ...
iq   2010 21                         55.30             299.334286
          22                         86.47             298.330000
          23                         58.94             296.598571
          24                         59.67             296.345714
          25                         63.22             298.097143

                      reanalysis_avg_temp_k  reanalysis_dew_point_temp_k  \
city year weekofyear
sj   1990 18                     297.742857                   292.414286
          19                     298.442857                   293.951429
          20                     298.878571                   295.434286
          21                     299.228571                   295.310000
          22                     299.664286                   295.821429
...                                     ...                          ...
iq   2010 21                     300.771429                   296.825714
          22                     299.392857                   296.452857
          23                     297.592857                   295.501429
          24                     297.521429                   295.324286
          25                     299.835714                   295.807143

                      reanalysis_max_air_temp_k  ...  \
city year weekofyear                             ...
sj   1990 18                              299.8  ...
          19                              300.9  ...
          20                              300.5  ...
          21                              301.4  ...
          22                              301.9  ...
...                                         ...  ...
iq   2010 21                              309.7  ...
          22                              308.5  ...
          23                              305.5  ...
          24                              306.1  ...
          25                              307.8  ...

                      reanalysis_precip_amt_kg_per_m2  \
city year weekofyear
sj   1990 18                                    32.00
          19                                    17.94
          20                                    26.10
          21                                    13.90
          22                                    12.20
...                                               ...
iq   2010 21                                    45.00
          22                                   207.10
          23                                    50.60
          24                                    62.33
          25                                    36.90

                      reanalysis_relative_humidity_percent  \
city year weekofyear
sj   1990 18                                     73.365714
          19                                     77.368571
          20                                     82.052857
          21                                     80.337143
          22                                     80.460000
...                                                    ...
iq   2010 21                                     88.765714
          22                                     91.600000
          23                                     94.280000
          24                                     94.660000
          25                                     89.082857

                      reanalysis_sat_precip_amt_mm  \
city year weekofyear
sj   1990 18                                 12.42
          19                                 22.82
          20                                 34.54
          21                                 15.36
          22                                  7.52
...                                            ...
iq   2010 21                                 55.30
          22                                 86.47
          23                                 58.94
          24                                 59.67
          25                                 63.22

                      reanalysis_specific_humidity_g_per_kg  \
city year weekofyear
sj   1990 18                                      14.012857
          19                                      15.372857
          20                                      16.848571
          21                                      16.672857
          22                                      17.210000
...                                                     ...
iq   2010 21                                      18.485714
          22                                      18.070000
          23                                      17.008571
          24                                      16.815714
          25                                      17.355714

                      reanalysis_tdtr_k  station_avg_temp_c  \
city year weekofyear
sj   1990 18                   2.628571           25.442857
          19                   2.371429           26.714286
          20                   2.300000           26.714286
          21                   2.428571           27.471429
          22                   3.014286           28.942857
...                                 ...                 ...
iq   2010 21                   9.800000           28.633333
          22                   7.471429           27.433333
          23                   7.500000           24.400000
          24                   7.871429           25.433333
          25                  11.014286           27.475000

                      station_diur_temp_rng_c  station_max_temp_c  \
city year weekofyear
sj   1990 18                         6.900000                29.4
          19                         6.371429                31.7
          20                         6.485714                32.2
          21                         6.771429                33.3
          22                         9.371429                35.0
...                                       ...                 ...
iq   2010 21                        11.933333                35.4
          22                        10.500000                34.7
          23                         6.900000                32.2
          24                         8.733333                31.2
          25                         9.900000                33.7

                      station_min_temp_c  station_precip_mm
city year weekofyear
sj   1990 18                        20.0               16.0
          19                        22.2                8.6
          20                        22.8               41.4
          21                        23.3                4.0
          22                        23.9                5.8
...                                  ...                ...
iq   2010 21                        22.4               27.0
          22                        21.7               36.6
          23                        19.2                7.4
          24                        21.0               16.0
          25                        22.2               20.4

[1456 rows x 21 columns]

In [16]:
# Remove `week_start_date` string.
X = X.drop('week_start_date', axis=1)

In [17]:
X

                       ndvi_ne   ndvi_nw   ndvi_se   ndvi_sw  \
city year weekofyear
sj   1990 18          0.122600  0.103725  0.198483  0.177617
          19          0.169900  0.142175  0.162357  0.155486
          20          0.032250  0.172967  0.157200  0.170843
          21          0.128633  0.245067  0.227557  0.235886
          22          0.196200  0.262200  0.251200  0.247340
...                        ...       ...       ...       ...
iq   2010 21          0.342750  0.318900  0.256343  0.292514
          22          0.160157  0.160371  0.136043  0.225657
          23          0.247057  0.146057  0.250357  0.233714
          24          0.333914  0.245771  0.278886  0.325486
          25          0.298186  0.232971  0.274214  0.315757

                      precipitation_amt_mm  reanalysis_air_temp_k  \
city year weekofyear
sj   1990 18                         12.42             297.572857
          19                         22.82             298.211429
          20                         34.54             298.781429
          21                         15.36             298.987143
          22                          7.52             299.518571
...                                    ...                    ...
iq   2010 21                         55.30             299.334286
          22                         86.47             298.330000
          23                         58.94             296.598571
          24                         59.67             296.345714
          25                         63.22             298.097143

                      reanalysis_avg_temp_k  reanalysis_dew_point_temp_k  \
city year weekofyear
sj   1990 18                     297.742857                   292.414286
          19                     298.442857                   293.951429
          20                     298.878571                   295.434286
          21                     299.228571                   295.310000
          22                     299.664286                   295.821429
...                                     ...                          ...
iq   2010 21                     300.771429                   296.825714
          22                     299.392857                   296.452857
          23                     297.592857                   295.501429
          24                     297.521429                   295.324286
          25                     299.835714                   295.807143

                      reanalysis_max_air_temp_k  reanalysis_min_air_temp_k  \
city year weekofyear
sj   1990 18                              299.8                      295.9
          19                              300.9                      296.4
          20                              300.5                      297.3
          21                              301.4                      297.0
          22                              301.9                      297.5
...                                         ...                        ...
iq   2010 21                              309.7                      294.5
          22                              308.5                      291.9
          23                              305.5                      292.4
          24                              306.1                      291.9
          25                              307.8                      292.3

                      reanalysis_precip_amt_kg_per_m2  \
city year weekofyear
sj   1990 18                                    32.00
          19                                    17.94
          20                                    26.10
          21                                    13.90
          22                                    12.20
...                                               ...
iq   2010 21                                    45.00
          22                                   207.10
          23                                    50.60
          24                                    62.33
          25                                    36.90

                      reanalysis_relative_humidity_percent  \
city year weekofyear
sj   1990 18                                     73.365714
          19                                     77.368571
          20                                     82.052857
          21                                     80.337143
          22                                     80.460000
...                                                    ...
iq   2010 21                                     88.765714
          22                                     91.600000
          23                                     94.280000
          24                                     94.660000
          25                                     89.082857

                      reanalysis_sat_precip_amt_mm  \
city year weekofyear
sj   1990 18                                 12.42
          19                                 22.82
          20                                 34.54
          21                                 15.36
          22                                  7.52
...                                            ...
iq   2010 21                                 55.30
          22                                 86.47
          23                                 58.94
          24                                 59.67
          25                                 63.22

                      reanalysis_specific_humidity_g_per_kg  \
city year weekofyear
sj   1990 18                                      14.012857
          19                                      15.372857
          20                                      16.848571
          21                                      16.672857
          22                                      17.210000
...                                                     ...
iq   2010 21                                      18.485714
          22                                      18.070000
          23                                      17.008571
          24                                      16.815714
          25                                      17.355714

                      reanalysis_tdtr_k  station_avg_temp_c  \
city year weekofyear
sj   1990 18                   2.628571           25.442857
          19                   2.371429           26.714286
          20                   2.300000           26.714286
          21                   2.428571           27.471429
          22                   3.014286           28.942857
...                                 ...                 ...
iq   2010 21                   9.800000           28.633333
          22                   7.471429           27.433333
          23                   7.500000           24.400000
          24                   7.871429           25.433333
          25                  11.014286           27.475000

                      station_diur_temp_rng_c  station_max_temp_c  \
city year weekofyear
sj   1990 18                         6.900000                29.4
          19                         6.371429                31.7
          20                         6.485714                32.2
          21                         6.771429                33.3
          22                         9.371429                35.0
...                                       ...                 ...
iq   2010 21                        11.933333                35.4
          22                        10.500000                34.7
          23                         6.900000                32.2
          24                         8.733333                31.2
          25                         9.900000                33.7

                      station_min_temp_c  station_precip_mm
city year weekofyear
sj   1990 18                        20.0               16.0
          19                        22.2                8.6
          20                        22.8               41.4
          21                        23.3                4.0
          22                        23.9                5.8
...                                  ...                ...
iq   2010 21                        22.4               27.0
          22                        21.7               36.6
          23                        19.2                7.4
          24                        21.0               16.0
          25                        22.2               20.4

[1456 rows x 20 columns]

# Data columns analysis

In [18]:
# Null check
pd.isnull(X).any()

ndvi_ne                                  True
ndvi_nw                                  True
ndvi_se                                  True
ndvi_sw                                  True
precipitation_amt_mm                     True
reanalysis_air_temp_k                    True
reanalysis_avg_temp_k                    True
reanalysis_dew_point_temp_k              True
reanalysis_max_air_temp_k                True
reanalysis_min_air_temp_k                True
reanalysis_precip_amt_kg_per_m2          True
reanalysis_relative_humidity_percent     True
reanalysis_sat_precip_amt_mm             True
reanalysis_specific_humidity_g_per_kg    True
reanalysis_tdtr_k                        True
station_avg_temp_c                       True
station_diur_temp_rng_c                  True
station_max_temp_c                       True
station_min_temp_c                       True
station_precip_mm                        True
dtype: bool

In [19]:
X.fillna(method='ffill', inplace=True)

/var/folders/ky/_ck3d0fs7b16dc9vvm30qjnh0000gn/T/ipykernel_30326/2672030822.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  X.fillna(method='ffill', inplace=True)

In [10]:
pd.isnull(X_train).any()

ndvi_ne                                  False
ndvi_nw                                  False
ndvi_se                                  False
ndvi_sw                                  False
precipitation_amt_mm                     False
reanalysis_air_temp_k                    False
reanalysis_avg_temp_k                    False
reanalysis_dew_point_temp_k              False
reanalysis_max_air_temp_k                False
reanalysis_min_air_temp_k                False
reanalysis_precip_amt_kg_per_m2          False
reanalysis_relative_humidity_percent     False
reanalysis_sat_precip_amt_mm             False
reanalysis_specific_humidity_g_per_kg    False
reanalysis_tdtr_k                        False
station_avg_temp_c                       False
station_diur_temp_rng_c                  False
station_max_temp_c                       False
station_min_temp_c                       False
station_precip_mm                        False
dtype: bool

In [20]:
print(X.shape)
print(y.shape)

(1456, 20)
(1456, 1)

In [21]:
#train_validation_split
X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=0.3,random_state=42)

In [22]:
# Create and train model
rf = RandomForestRegressor(n_estimators = 200, max_depth = 5, random_state = 18)
rf.fit(X_train, y_train)


# Predict on test data
prediction = rf.predict(X_val)
# Compute mean absolute error
mae_val = mean_absolute_error(y_val, prediction)
# Print results
print(mae_val)

/opt/miniconda3/envs/dsr-b38/lib/python3.12/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

18.68849065499948

In [23]:
y_train.mean()

total_cases    23.529931
dtype: float64

In [24]:
X_test = pd.read_csv('../data/01_raw/dengue_features_test.csv',
                             index_col=[0,1,2])
# Remove `week_start_date` string.
X_test = X_test.drop('week_start_date', axis=1)
X_test.fillna(method='ffill', inplace=True)

y_test = rf.predict(X_test)

/var/folders/ky/_ck3d0fs7b16dc9vvm30qjnh0000gn/T/ipykernel_30326/2319890867.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  X_test.fillna(method='ffill', inplace=True)

In [25]:
y_test.shape

(416,)

In [100]:
# Submission

df_sub_format = pd.read_csv("../data/01_raw/submission_format.csv")
city = df_sub_format.iloc[:, 0].values
year = df_sub_format.iloc[:, 1].values
weekofyear = df_sub_format.iloc[:, 2].values

df_submission = pd.DataFrame({"city" : city, "year" : year, "weekofyear" : weekofyear, "total_cases": y_test.astype(int)})
df_submission.to_csv("../data/submission.csv", index=False)

In [95]:
df_submission

    city  year  weekofyear  total_cases
0     sj  2008          18           16
1     sj  2008          19           15
2     sj  2008          20           12
3     sj  2008          21           21
4     sj  2008          22           34
..   ...   ...         ...          ...
411   iq  2013          22            6
412   iq  2013          23            3
413   iq  2013          24            3
414   iq  2013          25            4
415   iq  2013          26            3

[416 rows x 4 columns]